/**:
  ros__parameters:
    trajectory_execution:
      allowed_execution_duration_scaling: 3.0
      allowed_goal_duration_margin: 1.0
      allowed_start_tolerance: 0.05
      trajectory_duration_monitoring: true
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
    moveit_simple_controller_manager:
      controller_names:
        - joint_trajectory_controller
        - gripper_controller
      joint_trajectory_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - joint_1
          - joint_2
          - joint_3
          - joint_4
          - joint_5
          - joint_6
      # ParallelGripperCommand is not yet supported.
      # see https://github.com/moveit/moveit2/issues/3017
      gripper_controller:
        type: ParallelGripperCommand
        joints:
          - gripper_joint
        action_ns: gripper_cmd
        default: true
